IF NOT EXISTS ( SELECT  *
                FROM    SYSOBJECTS
                WHERE   XTYPE = 'U'
                        AND UPPER(NAME) = 'TB_CACHE_OBJECT' ) 
CREATE TABLE TB_CACHE_OBJECT
(
  CACHE_TYPE_ID INT PRIMARY KEY ,
  CACHE_TYPE_DESC NVARCHAR(100) ,
  CHANGE_TIME DATETIME
)