
IF EXISTS ( SELECT  *
            FROM    sysobjects
            WHERE   id = OBJECT_ID(N'[dbo].[pr_get_exchange_lay_cache]')
                    AND OBJECTPROPERTY(id, N'Isprocedure') = 1 ) 
    DROP PROCEDURE [dbo].[pr_get_exchange_lay_cache]
GO
CREATE PROCEDURE [dbo].[pr_get_exchange_lay_cache]
AS 

	SELECT * FROM 
	(
		SELECT ROW_NUMBER() OVER (PARTITION BY MARKET_ID ORDER BY ODDS DESC) AS TopNO,
		MATCH_ID,MARKET_ID,MATCH_TYPE,
		ODDS AS LayODDS,SUM(MATCH_AMOUNTS) LayMATCH_AMOUNTS 
		FROM 
			(
				SELECT MATCH_ID,MARKET_ID,ODDS,MATCH_AMOUNTS,MATCH_TYPE
				FROM TB_EXCHANGE_LAY 
				WHERE [STATUS]=1 and MATCH_TYPE = 1
			) tmp
		WHERE MARKET_ID IN(SELECT MARKET_ID FROM dbo.udf_get_canuse_market_for_betting())
		GROUP BY MATCH_ID,MARKET_ID,MATCH_TYPE,ODDS
		UNION ALL
		SELECT ROW_NUMBER() OVER (PARTITION BY MARKET_ID ORDER BY ODDS DESC) AS TopNO,
		MATCH_ID,MARKET_ID,MATCH_TYPE,
		ODDS AS LayODDS,SUM(MATCH_AMOUNTS) LayMATCH_AMOUNTS 
		FROM 
			(
				SELECT MATCH_ID,MARKET_ID,ODDS,MATCH_AMOUNTS,MATCH_TYPE
				FROM TB_EXCHANGE_LAY 
				INNER JOIN TB_CHAMP_EVENT ON TB_EXCHANGE_LAY.MATCH_ID = TB_CHAMP_EVENT.Champ_Event_ID
				WHERE TB_EXCHANGE_LAY.STATUS = 1 AND MATCH_TYPE = 2 AND TB_CHAMP_EVENT.Champ_Event_Status = 1
			) tmp
		GROUP BY MATCH_ID,MARKET_ID,MATCH_TYPE,ODDS
	)t 
	WHERE t.TopNO<=3
	
	SELECT MARKET_ID,MATCH_TYPE,(sum(BET_AMOUNTS)-sum(MATCH_AMOUNTS)) AS LayDealAmount,sum(MATCH_AMOUNTS) AS LayMatchAmount 
	From TB_EXCHANGE_Lay WITH(NOLOCK)
	WHERE [STATUS] < 6
	GROUP BY MARKET_ID,MATCH_TYPE

GO