if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[pr_up_system_account]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[pr_up_system_account]
GO

CREATE PROCEDURE [dbo].[pr_up_system_account]
(
@USER_ID INT,
 @USER_NAME NVARCHAR(40),
 @BORN_YEAR NVARCHAR(4), 
 @BORN_MONTH NVARCHAR(2), 
 @BORN_DAY NVARCHAR(2), 
 @EMAIL_ADDRESS NVARCHAR(50), 
 @COUNTRY INT, 
 @CITY NVARCHAR(50), 
 @ADDRESS NVARCHAR(100), 
 @ZIP_CODE NVARCHAR(10), 
 @PHONE_TYPE INT, 
 @PHONE_ZONE NVARCHAR(5),
 @PHONE_NUMBER NVARCHAR(20), 
 @LOGIN_NAME NVARCHAR(20), 
 @PASSWORD NVARCHAR(200),
 @SQUESTION1 INT, 
 @SANSWER1 NVARCHAR(100), 
 @ROLE_ID INT, 
 @ACCOUNT_STATUS INT, 
 @AGENT_ID INT,
 @CURRENCY_ID INT,
 @TIMEZONE_ID INT
 
)
AS
BEGIN
UPDATE dbo.TB_SYSTEM_ACCOUNT
SET  [USER_NAME]=@USER_NAME, 
BORN_YEAR=@BORN_YEAR, 
BORN_MONTH=@BORN_MONTH, 
BORN_DAY=@BORN_DAY, 
EMAIL_ADDRESS=@EMAIL_ADDRESS, 
COUNTRY=@COUNTRY, 
CITY=@CITY, 
[ADDRESS]=@ADDRESS, 
ZIP_CODE=@ZIP_CODE, 
PHONE_TYPE=@PHONE_TYPE, 
PHONE_ZONE=@PHONE_ZONE,
PHONE_NUMBER=@PHONE_NUMBER, 
LOGIN_NAME=@LOGIN_NAME, 
[PASSWORD]=@PASSWORD, 
SQUESTION1=@SQUESTION1, 
SANSWER1=@SANSWER1, 
ROLE_ID=@ROLE_ID, 
ACCOUNT_STATUS=@ACCOUNT_STATUS, 
AGENT_ID=@AGENT_ID,
CURRENCY_ID=@CURRENCY_ID,
TIMEZONE_ID=@TIMEZONE_ID
WHERE [USER_ID]=@USER_ID;
select @USER_ID;
END

GO