if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[pr_add_system_account]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[pr_add_system_account]
GO

CREATE PROCEDURE [dbo].[pr_add_system_account]
(
 @USER_NAME				NVARCHAR(40),
 @BORN_YEAR				NVARCHAR(4), 
 @BORN_MONTH			NVARCHAR(2), 
 @BORN_DAY				NVARCHAR(2), 
 @EMAIL_ADDRESS			 NVARCHAR(50), 
 @COUNTRY				INT, 
 @CITY						NVARCHAR(50), 
 @ADDRESS					NVARCHAR(100), 
 @ZIP_CODE					NVARCHAR(10), 
 @PHONE_TYPE				INT, 
 @PHONE_ZONE				NVARCHAR(5),
 @PHONE_NUMBER				NVARCHAR(20), 
 @LOGIN_NAME				 NVARCHAR(20), 
 @PASSWORD				NVARCHAR(200),
 @SQUESTION1			INT, 
 @SANSWER1				NVARCHAR(100), 
 @ROLE_ID					INT, 
 @ACCOUNT_STATUS		INT, 
 @AGENT_ID				INT,
 @CURRENCY_ID			INT,
 @TIMEZONE_ID			INT

)
AS
BEGIN
     DECLARE @ID INT;
	INSERT INTO dbo.TB_SYSTEM_ACCOUNT( [USER_NAME], BORN_YEAR, BORN_MONTH, BORN_DAY, EMAIL_ADDRESS, COUNTRY, CITY, [ADDRESS], ZIP_CODE, PHONE_TYPE, PHONE_ZONE,PHONE_NUMBER, LOGIN_NAME, [PASSWORD], SQUESTION1, SANSWER1, ROLE_ID, ACCOUNT_STATUS, AGENT_ID,CURRENCY_ID,TIMEZONE_ID)
VALUES( @USER_NAME, @BORN_YEAR, @BORN_MONTH, @BORN_DAY, @EMAIL_ADDRESS, @COUNTRY, @CITY, @ADDRESS, @ZIP_CODE, @PHONE_TYPE, @PHONE_ZONE,@PHONE_NUMBER, @LOGIN_NAME, @PASSWORD, @SQUESTION1, @SANSWER1, @ROLE_ID, @ACCOUNT_STATUS, @AGENT_ID,@CURRENCY_ID,@TIMEZONE_ID);
select @ID=SCOPE_IDENTITY();
EXEC	pr_inti_userfund @ID ;
select @ID
END

GO