-- =============================================
-- Script Template
-- =============================================
if(not exists(select * from TB_SYSTEM_FUNC where FUNC_ID=9301))
begin
	-- 9301 申请总代理（页面）
	INSERT INTO TB_SYSTEM_FUNC(FUNC_ID,PARENT_FUNC_ID,FUNC_NAME,FUNC_TYPE,LEVELNO,FUNC_ORDER,URL)
	VALUES(9301,9000,'申请总代理',2,2,6,'');
END


--代理申请管理（页面）
INSERT INTO TB_SYSTEM_FUNC(FUNC_ID,PARENT_FUNC_ID,FUNC_NAME,FUNC_TYPE,LEVELNO,FUNC_ORDER,URL)
VALUES(1301,1000,'代理申请管理',1,2,7,'');
--代理申请审批（权限）
INSERT INTO TB_SYSTEM_FUNC(FUNC_ID,PARENT_FUNC_ID,FUNC_NAME,FUNC_TYPE,LEVELNO,FUNC_ORDER,URL)
VALUES(1302,1301,'代理申请审批',1,3,1,'');
--1303 代理批准审批（权限）
INSERT INTO TB_SYSTEM_FUNC(FUNC_ID,PARENT_FUNC_ID,FUNC_NAME,FUNC_TYPE,LEVELNO,FUNC_ORDER,URL)
VALUES(1303,1301,'代理申请审批',1,3,1,'');
--1304 代理拒绝审批（权限）
INSERT INTO TB_SYSTEM_FUNC(FUNC_ID,PARENT_FUNC_ID,FUNC_NAME,FUNC_TYPE,LEVELNO,FUNC_ORDER,URL)
VALUES(1304,1301,'代理申请审批',1,3,1,'');


--管理员默认权限
INSERT  INTO dbo.TB_ROLE_FUNC_MAP ( ROLE_ID, FUNC_ID )VALUES  ( 1, 1301 )     
INSERT  INTO dbo.TB_ROLE_FUNC_MAP ( ROLE_ID, FUNC_ID )VALUES  ( 1, 1302 )
INSERT  INTO dbo.TB_ROLE_FUNC_MAP ( ROLE_ID, FUNC_ID )VALUES  ( 1, 1303 )
INSERT  INTO dbo.TB_ROLE_FUNC_MAP ( ROLE_ID, FUNC_ID )VALUES  ( 1, 1304 )
